-- Attendance submissions stay pending until an administrator approves them.
create table if not exists public.pending_attendance (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  event_key text not null,
  event_name text not null,
  event_type text not null check (event_type in ('activity', 'meeting', 'event', 'project')),
  event_date date,
  volunteer_hours numeric(6,2) check (volunteer_hours is null or volunteer_hours > 0),
  guest_name text,
  guest_email text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by bigint references public.members(id),
  reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now()
);

do $$
begin
  alter table public.pending_attendance drop constraint if exists pending_attendance_event_type_check;
  alter table public.pending_attendance add constraint pending_attendance_event_type_check
    check (event_type in ('activity', 'meeting', 'event', 'project'));
end $$;

create index if not exists pending_attendance_status_idx on public.pending_attendance(status, created_at desc);
create index if not exists pending_attendance_member_idx on public.pending_attendance(member_id, created_at desc);

create table if not exists public.attendance_guests (
  id bigint generated by default as identity primary key,
  pending_attendance_id bigint not null unique references public.pending_attendance(id),
  member_id bigint not null references public.members(id) on delete cascade,
  event_name text not null,
  event_date date,
  guest_name text not null,
  guest_email text,
  created_at timestamptz not null default now()
);

create index if not exists attendance_guests_member_idx on public.attendance_guests(member_id, created_at desc);

alter table public.pending_attendance enable row level security;
alter table public.attendance_guests enable row level security;

do $$
begin
  create policy pending_attendance_member_select on public.pending_attendance
    for select using (exists (
      select 1 from public.members m where m.id = member_id and m.user_id = auth.uid()
    ));
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy attendance_guests_member_select on public.attendance_guests
    for select using (exists (
      select 1 from public.members m where m.id = member_id and m.user_id = auth.uid()
    ));
exception when duplicate_object then null;
end $$;
